arch: 
  - ppc64le
  - amd64
  
dist: bionic
sudo: required
service: docker

script:
  - w
  - docker pull ubuntu:18.04 > /dev/null
  - docker run -i ubuntu:18.04 bash -c 'who'
  - docker run -t ubuntu:18.04 bash -c 'who'
  - docker run -it ubuntu:18.04 bash -c 'who'

